### ISSUE TITLE
Improve data management

### ISSUE THREAD

**Issue by ManuelAlvarezC** [sdv-dev/Copulas#11]
Don’t store iris dataset on repo,  download it using sklearn.load_data

**Comment by echo66** [comment]
Question: if you are going to include sklearn as a dependency, wouldn't it be a good idea to replace the current KDE implementation with the one from sklearn?

**Comment by ManuelAlvarezC** [comment]
Hi @echo66, and thanks for your suggestion.

Would you mind elaborating a little why do you think the KDE implementation from `sklearn` is better than the one from `scipy`?

**Comment by csala** [comment]
This is not related to the current project status any more.
