### ISSUE TITLE
Handle multiple features that are not normally distributed in Copulas

### ISSUE THREAD

**Issue by dmey** [sdv-dev/Copulas#110]
When creating synthetic samples from data that are not normally distributed, understandably, using `copulas.multivariate.GaussianMultivariate` creates samples with symmetry from the mean even when the data are of arbitrary distributions. This may therefore lead to very different results between the original sample space and the synthetically generated data.

How can one create synthetic samples for data with multidimensional features (see #109) and where the features are not normally distributed?

**Comment by dmey** [comment]
Continuing from : https://github.com/DAI-Lab/Copulas/issues/109#issuecomment-546121423

> This is a known limitation of Copulas at the moment: when using multivariate Copulas you can specify which univariate distribution to use, but you are limited to using the same one for all the variables.
This is something that we have had in mind for some time already, and one of the highest priority features to come in the next releases, but unfortunately its development has not been started yet.

@csala thanks for the info. Do you have an ETA for a new release? I only discover this project a few hours ago but if you have a plan / we can create a plan, I may be able to also contribute to this.

**Comment by dmey** [comment]
@csala I have created an example below that should help test with this 'issue':

``` py
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from copulas.multivariate import GaussianMultivariate

# Create a dataset containign two features based on differenet dist.
original_exp = np.random.exponential(scale=1, size=1000)
original_norm = np.random.normal(loc=0, scale=1, size=1000)
samples_original = pd.DataFrame({'original_exp': original_exp, 'original_norm': original_norm})

# Compute new samples based on the original datasets -- this assumes data normally dist.
copula = GaussianMultivariate()
copula.fit(samples_original)
num_samples = 1000
samples_copula = copula.sample(num_samples)
samples_copula.columns = ['copula_exp', 'copula_norm']

samples = pd.concat([samples_original, samples_copula], axis=1)
samples.hist()
plt.show()
```

![image](https://user-images.githubusercontent.com/26348635/67618377-85bff780-f7e6-11e9-94e4-89bf72e69231.png)

Predictably, as the univariate distribution used for both is Gaussian, the new samples have been remapped to a normal distribution from the original exponential distribution ('original_exp').

I think that here there are two issues in order to implement be able to implement this in Copulas : (a) recognise the sample distribution, and (b) allow the use of multiple univariate distributions. 

Re (a), I think that this is somewhat related to (if not same as) #47. I think that something similar as  proposed in https://stackoverflow.com/a/37616966 and https://stackoverflow.com/a/37570540 is doable (may want to consider/discuss the type of fit to use).

Re (b), I think that this would be the main reason for using a copula -- i.e. whether the marginals of a multivariate distribution like in the example above are different. I may have missed something here but if the general copula function has already been implemented in Copulas, (b) should just be a matter of creating the copula function from the marginals in (a) -- I was looking at https://www.jstor.org/stable/23012317.

**Comment by csala** [comment]
This has been covered in the latest release [v0.3.0](https://github.com/sdv-dev/Copulas/releases/tag/v0.3.0), so I'm closing the issue for now.

Here is are the relevant documentation links:
- https://sdv-dev.github.io/Copulas/tutorials/03_Multivariate_Distributions.html#Specifying-column-distributions
- https://sdv-dev.github.io/Copulas/tutorials/02_Univariate_Distributions.html#Selecting-the-best-Univariate

Please feel free to re-open it (or open a new one) if anything else needs to be added.
