### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy.testing.decorators' 

### ISSUE THREAD

**Issue by david2588e** [sdv-dev/Copulas#128]
* Copulas version:0.2.5 from pip install 
* Python version:3.6
* Operating System:win 10

### Description

Describe what you were trying to get done.

running the example.py in virtualenv
and spyder is installed in virtualenv

Tell us what happened, what went wrong, and what you expected to happen.
ModuleNotFoundError: No module named 'numpy.testing.decorators'
### What I Did
update 
scipy 1.0.0
numpy 1.18.1
```
Paste the command(s) you ran and the output.
Traceback (most recent call last):

  File "<ipython-input-4-36fc6def36fc>", line 1, in <module>
    runfile('G:/Tushare/Copulas-master/Copulas-master/examples/example.py', wdir='G:/Tushare/Copulas-master/Copulas-master/copulas')

  File "C:\Users\Liu\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\Liu\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G:/Tushare/Copulas-master/Copulas-master/examples/example.py", line 5, in <module>
    from copulas.multivariate.GaussianCopula import GaussianCopula

  File "G:\Tushare\Copulas-master\Copulas-master\copulas\multivariate\__init__.py", line 2, in <module>
    from copulas.multivariate.gaussian import GaussianMultivariate

  File "G:\Tushare\Copulas-master\Copulas-master\copulas\multivariate\gaussian.py", line 6, in <module>
    from scipy import integrate, stats

  File "C:\Users\Liu\Anaconda3\lib\site-packages\scipy\stats\__init__.py", line 345, in <module>
    from .morestats import *

  File "C:\Users\Liu\Anaconda3\lib\site-packages\scipy\stats\morestats.py", line 12, in <module>
    from numpy.testing.decorators.deprecated import setastest

ModuleNotFoundError: No module named 'numpy.testing.decorators'

If there was a crash, please include the traceback here.
```

**Comment by csala** [comment]
Hi @david2588e 

Unfortunately, Copulas does not work with `numpy` versions higher than 1.7, as you can see in the dependency specification in the `setup.py`: https://github.com/sdv-dev/Copulas/blob/1d434f9cb7cd22d88715513722962399fdc7b293/setup.py#L15

Please downgrade numpy to the specified range of versions and let us know if the error still shows up.

Also, please check the master branch, as newer and more comprehensive examples were uploaded yesterday.

**Comment by david2588e** [comment]
Thanks a lot!

Is there Frank Copula example to handle time series for this?


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Carles Sala<mailto:notifications@github.com>
发送时间: 2020年2月7日 6:23
收件人: sdv-dev/Copulas<mailto:Copulas@noreply.github.com>
抄送: david2588e<mailto:liujinyi@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [sdv-dev/Copulas] ModuleNotFoundError: No module named 'numpy.testing.decorators' (#128)


Hi @david2588e<https://github.com/david2588e>

Unfortunately, Copulas does not work with numpy versions higher than 1.7, as you can see in the dependency specification in the setup.py: https://github.com/sdv-dev/Copulas/blob/1d434f9cb7cd22d88715513722962399fdc7b293/setup.py#L15

Please downgrade numpy to the specified range of versions and let us know if the error still shows up.

Also, please check the master branch, as newer and more comprehensive examples were uploaded yesterday.

―

**Comment by csala** [comment]
I'm not sure about you mean exactly but, in general, Copulas does not have specific support for time series and there is no intention to add it in the future.
However, you might want to keep an eye on [SDV](/sdv-dev/SDV), which will be adding support for time-series data soon.

Also, if the original doubt is resolved please feel free to close this issue.
