### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by k15z** [sdv-dev/Copulas#146]
We can test the end-to-end behavior of Copulas by (1) testing to make sure it works with SDV/RDT and (2) feeding a bunch of datasets from S3 through it. The unit test folder can be reorganized into

```
tests/
    unit/ <- the current tests go here
    integration/ <- SDV/RDT/S3
    mathematical/ <- see issue #144
```

**Comment by csala** [comment]
Mostly covered in #153, #159, #164 and #165.
Closing this for now, and later on a new issue can be opened to cover the SDV integration part.
