### ISSUE TITLE
The sample methods of Frank and Gumbel return incorrect results

### ISSUE THREAD

**Issue by remem9527** [sdv-dev/Copulas#155]
* Copulas version:0.2.5
* Python version:3.7 
* Operating System: macOS

### Description

The reason is the order of parameters in `percent_point`  are wrong.

One solution is change line 116 in `Frank.py` and line 97 in ` Gumbel.py` to:

```
minimum = brentq(self.partial_derivative_scalar, EPSILON, 1.0, args=(_V, _y))
```

And also, the inverse of conditional distribution function has analytic expressions for Frank. So, no need for solve the equation.

**Comment by csala** [comment]
Hello @remem9527 during the last few weeks there was a huge cleanup and refactoring work in the Copulas project that included numerical testing against well-known and trusted implementations such as Matlab, so we are sure that this is not an issue anymore.

I'm closing it for now, but please feel free to reopen it (or open a new one) if you detect something wrong again.
