### ISSUE TITLE
scipy <1.3 dependency

### ISSUE THREAD

**Issue by MattWenham** [sdv-dev/Copulas#180]
* Copulas version: 0.3.1
* Python version: 3.7.8
* Operating System: Windows 10

### Description

Is the scipy dependency <1.3 still necessary, and if so why not later versions?

**Comment by csala** [comment]
Hello @MattWenham 

The versions are all capped to the next major (or in some cases minor) version of the libraries to avoid incompatibility surprises when they change the API.

For scipy in particular it seems like newer versions are indeed compatible, so we will be expanding the support range soon.
