### ISSUE TITLE
VineCopula is not working NonImplementedError for pdf and cdf

### ISSUE THREAD

**Issue by grechasneak** [sdv-dev/Copulas#370]
### Environment Details

* Copulas version: 3.10.4
* Python version: 1.4.2
* Operating System: Linux

### Error Description
Trying to fit a vine copula to a pandas dataframe with 3 columns and then get the pdf for each row in the dataset. I am getting a NonImplementedError.

![image](https://github.com/sdv-dev/Copulas/assets/25159822/4eab22a1-b7e6-4c2b-86bd-a7485dea6200)

**Comment by npatki** [comment]
Hi @grechasneak, a `NotImplementedError` indicates that the functionality does not exist for the type of Copula you're using.

I would recommend referring to the [API docs for Vine Copulas](https://sdv.dev/Copulas/api/copulas.multivariate.vine.html). In the docs, I don't see any method called `probability_density`. Did you meant to use a different method such as [get_likelihood](https://sdv.dev/Copulas/api/copulas.multivariate.vine.html#copulas.multivariate.vine.VineCopula.get_likelihood)?

Alternatively, probability density is something that's missing, we could turn this into a feature request for adding such functionality. We prioritize feature requests based on demand and the importance to your projects. So any other information about your project will be useful. For example, what is the goal of the project? Are you trying to predict something for the selected weather?

**Comment by npatki** [comment]
Closing this issue off since it has been stale for some time. Please feel free to reply if there is more to discuss and I can always re-open the issue for continued investigation.
