### ISSUE TITLE
Digital Object Indentifier for Copulas

### ISSUE THREAD

**Issue by arfogg** [sdv-dev/Copulas#387]
### Problem Description

I work in academic space science research. When publishing research, journals are becoming more strict about citing the code that has been used, often requiring a digital object identifier (DOI). See example here:
https://www.agu.org/publish-with-agu/publish/author-resources/data-and-software-for-authors
Scroll to "Data & Software Citation":
"
Citations should include:

1. Author(s) or project name(s)
2. Date / Software published
3. Title / Software name
4. Data or software release/version (optional)
5. Bracketed description type (e.g., [Dataset], [Software], [Collection], [ComputationalNotebook])
6. Repository name / Publication venue
7. **DOI, persistent identifier, URL**
8. Retrieved date (required when using URL)

"

### Additional context

It would be really great if you could generate a DOI for new releases of Copulas. It's quite easy to do, instructions here: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content. An added benefit is it would give you an indication of where/how your great package is being used in academic literature.

**Comment by srinify** [comment]
Hi @arfogg this is a great idea! We're going to work on adding DOI's for each version of our core libraries.

**Comment by srinify** [comment]
Closing out this issue since we have the other issue in SDV already. Let's use that for tracking instead!

**Comment by npatki** [comment]
For future ref, this is the SDV issue: https://github.com/sdv-dev/SDV/issues/1878

Marking as duplicate
