### ISSUE TITLE
.fit method parameter

### ISSUE THREAD

**Issue by helderc** [sdv-dev/Copulas#389]
Hi all. First, thanks for the great library!

Considering the `GaussianMultivariate` as an example, does the input of `.fit` method expect the last column to be the samples' classes?

I'm asking because it is not mentioned in the documentation [1] that only shows the parameter `X`. But looking at the example [2], we see the concatenation of X and y. If the example is correct, maybe we should update the doc for clarification?

[1] https://sdv.dev/Copulas/api/copulas.multivariate.gaussian.html#copulas.multivariate.gaussian.GaussianMultivariate

[2] https://sdv.dev/Copulas/tutorials/04_Syntehtic_Data_for_Machine_Learning.html

**Comment by srinify** [comment]
Hi there @helderc 👋 I'd encourage you to give SDV a try, specifically the [GaussianCopulaSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/gaussiancopulasynthesizer). This synthesizer class is a drop-in replacement for GaussianMultivariate. SDV is a framework that sits one layer above our Copulas library and offers a significantly better user experience. 

I'm also curious to know what your use case is for using gaussian copulas?

**Comment by srinify** [comment]
Closing this issue for now since GaussianCopulaSynthesizer is our recommended path forward! If you have more questions, you're welcome to join our Slack and we can also discuss more there: https://bit.ly/sdv-slack-invite

**Comment by helderc** [comment]
Thanks for the feedback @srinify , I'll definitely check SDV out.
