### ISSUE TITLE
discrete distribution

### ISSUE THREAD

**Issue by pyni** [sdv-dev/Copulas#416]
### Environment details

If you are already running Copulas, please indicate the following details about the environment in
which you are running it:

* Copulas version: new
* Python version: 3.7
* Operating System: ubuntu18.04

### Problem description

Hi, May I know whether this library can be used for discrete distribution, such as two multinormial distribution?

I did not find the code for this part.

Thanks.

**Comment by pyni** [comment]
And do you have any way for me to cite?

**Comment by srinify** [comment]
Hi there @pyni 👋 Sorry for the delay, just catching up to your question!

To clarify -- do you want to form a discrete distribution that's a mixture of 2 multi-nomial distributions?

Re: citing -- we're still working on adding DOI's to our GitHub repos for citing. Stay tuned!

**Comment by srinify** [comment]
Hi there @pyni I haven't heard from you in 2 weeks so our policy is to generally close out the issue. Feel free to open a new one if you have more to add about your original feature request and I look forward to seeing you around in our community :)
